# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Build and Test
        run: |          
          npm install @angular/cli
          npm install
          ./node_modules/@angular/cli/bin/ng build --prod --build-optimizer --progress=false
          ./node_modules/@angular/cli/bin/ng test --watch=false
          ./node_modules/@angular/cli/bin/ng lint
      - name: Security scan

      - name: Deployment to AWS
        run:
          echo "$(ls -la)"
          echo "$(ls -la dist)"
          ssh ubuntu@ec2-3-22-120-211.us-east-2.compute.amazonaws.com rm -rf demo-tmp
          scp -r dist/demo ubuntu@ec2-3-22-120-211.us-east-2.compute.amazonaws.com:demo-tmp
          ssh ubuntu@ec2-3-22-120-211.us-east-2.compute.amazonaws.com sudo rm -rf /var/www/html/demo
          ssh ubuntu@ec2-3-22-120-211.us-east-2.compute.amazonaws.com sudo mv demo-tmp /var/www/html/demo
